---
groups:
- name: webhook
  jobs:
  - test-webhook
  
resource_types:
- name: dynatrace-resource
  type: docker-image
  source:
    repository: jbraeuer/dynatrace-resource
#    tag: 0.0.1 

resources:
- name: dynatrace
  type: dynatrace-resource
  check_every: 2m
  source:
    apitoken: ((apitoken))
    tenanthost: ((tenanthost))
  webhook_token: DTTOKEN

#- name: git-webhook
#  type: git
#  webhook_token: DTTOKEN
#  check_every: 5m
#  source:
#    branch: master
#    uri: https://github.com/johannes-b/webhook.git

#- name: webhook-time
#  type: time
#  source:
#    interval: 2m
#    start: 10:00 AM
#    stop: 12:00 AM
#  webhook_token: DTTOKEN

jobs:
- name: test-webhook
  plan:
  - get: dynatrace
    trigger: true
  - task: run-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Webhook works!"
